- name: 'Provision Image'
  hosts: localhost
  become: true

  tasks:
    - name: install mysql
      apt: name=mysql-server state=present

    - name: install python mysql module
      apt: name=python-mysqldb state=present

    - name: create database
      mysql_db:
        name: wordpress
        state: present
        encoding: utf8mb4

    - name: create user
      mysql_user:
        name: wordpress
        password: wordpress
        priv: "*.*:ALL,GRANT"
        state: present
        host: "%"